### ISSUE TITLE
Cannot seem to make work on 10.11.1 for dual displays 

### ISSUE THREAD

**Issue by brianjking** [gbrueckner/Snapp#1]
Hello,

Does Snapp currently have any functionality when using two displays? I'm currently only able to get it to snap a window to be in a maximized (but not full screen/immersive mode) on either my MacBook Pro display or my external monitor. If I drag another app to this screen it simply does the same thing to this application as well, instead of splitting the view.

Thanks!

**Comment by gbrueckner** [comment]
Snapp doesn't integrate with Apple's own Split View, so windows are never moved in full screen / immersive mode. Is that what you meant?
