### ISSUE TITLE
Questioning about Snapp not working on Google Chrome windows

### ISSUE THREAD

**Issue by vjestin** [gbrueckner/Snapp#9]
Hi,

I installed and used Snapp successfully lately. Great app! However, the snapping was not working on Google Chrome windows.

I tried to understand why by reading the code. I think the problem is coming from line 71 in `CGWindow+Additions.c`:

`
if (windowName == NULL || title == NULL || CFStringCompare(windowName, title, 0) == kCFCompareEqualTo) {
`

* `windowName` is fetched from the `CGWindowListCopyWindowInfo` call.
* `title` is fetched from the `AXUIElementGetTitle` call.

If you have a Google Chrome active tab displaying a web page of which title is "John Doe", then:

* `windowName` will be "John Doe".
* `title` will be "John Doe - Google Chrome".

I "fixed" the issue by replacing the `CFStringCompare` part with something like `title starts with windowName` and it worked. However it is not a good fix (why this way and not the other one?).

I actually do not have the level of expertise to figure out if the issue is in Google Chrome or in Snapp.

Is an application expected to provide the same names for windows in Core Graphics and Application Services? Or is not safe to rely on those elements to determine if we found the good window reference?

I came here in the first place to get your opinion on this topic rather than trying to show the issue to the chromium community.

I'm running High Sierra with Google Chrome 70.

Thanks for reading.

**Comment by gbrueckner** [comment]
Hi, thanks for the report and the careful analysis! The problem at the core of all this is that there is no publically available direct translation from the mac OS public accessibility API to the window hierarchy. As a temporary fix, I will reintroduce a private API that does this job.
